### ISSUE TITLE
Loading spinner flash on query

### ISSUE THREAD

**Issue by gregsantos** [gregsantos/fcl-next-harness#7]

**Comment by huyndo** [comment]
That's expected because we're waiting for the query to be finished before the spinner goes away.

**Comment by gregsantos** [comment]
not sure consecutive queries should block ui?

**Comment by huyndo** [comment]
Like if you press query multiple times? I mean we can just not wait for query to be resolved in CMD and it will just print out the result when it's done. That will get rid of the spinner.
